name: List Artifacts and Dependencies

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to run the workflow on'
        required: true
        default: 'develop'
      VERSION:
        description: 'Artifact version to search for'
        required: true

jobs:
  list-artifacts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: List Artifacts and Dependencies
        run: |
          # Search for all POM files in the repository
          pom_files=$(find . -name 'pom.xml')

          # Extract the dynamically provided artifact version from the user input
          VERSION=${{ github.event.inputs.VERSION }}
          
          # Search for the artifact version in POM files
          echo "Searching for artifact version: $VERSION"
          for file in $pom_files; do
            if grep -qE "<version>$VERSION</version>|<version>${VERSION}-SNAPSHOT</version>" $file; then
              echo "Artifact version $VERSION found in $file."
            fi
          done || true
