name: List Artifacts and Dependencies

on:
  push:
    branches:
      - develop

jobs:
  list-artifacts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: List Artifacts and Dependencies
        run: |
          # Search for all POM files in the repository
          pom_files=$(find . -name 'pom.xml')

          # Loop through each POM file and extract artifact and dependency information
          for file in $pom_files; do
            echo "Artifacts and Dependencies in $file:"
            grep -E "<artifactId>|<version>|<dependency>\s*<version>" $file | awk -F '[<>]' '/<artifactId>/ || /<version>/ || /<dependency>\s*<version>/{print $3}' | paste -d ' ' - - -
            ls
          done
