name: List Artifacts and Dependencies

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to run the workflow on'
        required: true
        default: 'develop'
      VERSION:
        description: 'Artifact version to search for'
        required: true

jobs:
  list-artifacts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: List Artifacts and Dependencies
        run: |
          # Search for all POM files in the repository
          pom_files=$(find . -name 'pom.xml')

          # Loop through each POM file and extract artifact and dependency information
          for file in $pom_files; do
            # Extract artifacts and dependencies from the POM file
            artifacts=$(grep -E "<groupId>io.mosip</groupId>|<artifactId>" $file | awk -F '[<>]' '/<artifactId>/{print $3}')
            dependencies=$(grep -E "<groupId>io.mosip</groupId>|<artifactId>" $file | awk -F '[<>]' '/<dependency>/{print $3}')

            # Combine artifact and dependency information
            all_elements="$artifacts $dependencies"

            # Check if the provided version is present in the POM file
            if echo "$all_elements" | grep -qw "$VERSION"; then
              echo "Artifact version $VERSION found in $file for artifacts and dependencies: $all_elements."
            fi
          done
