name: Developer Pre-Release Check

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to run the workflow on'
        required: true
        default: 'develop'
      VERSION:
        description: 'version_to_check'
        required: true

jobs:
  pre-release-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: List Artifacts and Dependency Versions
        run: |
          # Your script or command to list artifacts and dependencies
          grep -E -o '<artifactId>[^<]+</artifactId>|<version>[^<]+</version>' $(find . -name 'pom.xml') | awk 'BEGIN {ORS="\n"} {print} /^<artifactId>/ {printf("\n")}'
          # Example command: python list_artifacts.py

      - name: Check Dynamically Provided Artifact Version
        run: |
          # Your script or command to check dynamically provided artifact version
          version_to_check="${{ inputs.VERSION }}"
          if ! grep -r -E "<artifactId>[^<]+</artifactId>|<version>${version_to_check}</version>" --include="pom.xml" .; then
            echo "Error: Dynamically provided artifact version not found."
            exit 1
          fi

# Example command: python check_version.py 2.0.1
