name: Check Artifact Version

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to run the workflow on'
        required: true
        default: 'develop'
      VERSION:
        description: 'Artifact version to search for'
        required: true

jobs:
  check-artifact-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Check Artifact Version
        run: |
          # Extract the dynamically provided artifact version from the user input
          VERSION=${{ github.event.inputs.VERSION }}
          
          # Search for the artifact version in POM files as artifact or dependency version
          echo "Searching for artifact version: $VERSION"
          for file in $(find . -type f -name '*.xml' ! -name 'pom.xml'); do
            echo "Contents of $file:"
            cat $file
            if grep -qE "<version>$VERSION</version>|<dependency>\s*<version>$VERSION</version>|<version>$VERSION-SNAPSHOT</version>|<dependency>\s*<version>$VERSION-SNAPSHOT</version>" $file; then
              echo "Artifact version $VERSION found in $file."
            fi
          done || true

