name: Check Artifact Version

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to run the workflow on'
        required: true
        default: 'develop'
      VERSION:
        description: 'Artifact version to search for'
        required: true

jobs:
  check-artifact-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Check Artifact Version
        run: |
          # Extract the dynamically provided artifact version from the user input
          VERSION=${{ github.event.inputs.VERSION }}
          
          # Search for the artifact version in POM files as artifact or dependency version
          echo "Searching for artifact version: $VERSION"
          files=$(find . -type f -name '*.xml' ! -name 'pom.xml' -print0 | xargs -0 grep -l -E "<version>$VERSION</version>|<dependency>\s*<version>$VERSION</version>|<version>$VERSION-SNAPSHOT</version>|<dependency>\s*<version>$VERSION-SNAPSHOT</version>" | sort -u)

          if [ -z "$files" ]; then
            echo "Artifact version $VERSION not found in any POM files."
            exit 1
          else
            echo "Artifact version $VERSION found in the following files:"
            echo "$files"
          fi
