name: Pre-release Checklist

on:
  pull_request:
    types:
      - synchronize
      - opened
      - reopened

jobs:
  check-versions:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Grant permissions
        run: |
          chmod +x ./pre-registration/pom.xml

      - name: Check Artifact Version
        run: |
          # Extract the dynamically provided artifact version from your context
          ARTIFACT_VERSION=${{ secrets.DYNAMIC_ARTIFACT_VERSION }}

          # Search for the artifact version in POM files as artifact or dependency version
          echo "Searching for artifact version: $ARTIFACT_VERSION"
          files=$(find . -type f -name '*.xml' ! -name 'pom.xml' -print0 | xargs -0 grep -l -E "<artifactId>|<version>$ARTIFACT_VERSION</version>|<dependency>\s*<version>$ARTIFACT_VERSION</version>" | sort -u)

          # List all artifacts and their dependent versions
          for file in $files; do
            echo "Artifact in $file:"
            grep -E "<artifactId>|<version>|<dependency>\s*<version>" $file | awk -F '[<>]' '/<artifactId>/ || /<version>/ || /<dependency>\s*<version>/{print $3}' | paste -d ' ' - - -
          done
