name: Check Artifact Version

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to run the workflow on'
        required: true
        default: 'develop'
      VERSION:
        description: 'Artifact version to search for'
        required: true

jobs:
  check-artifact:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check Artifact Version
        run: |
          # Extract the dynamically provided artifact version from the user input
          VERSION=${{ github.event.inputs.VERSION }}

          # Search for the artifact version in POM files
          echo "Searching for artifact version: $VERSION"
          found=false
          for file in $(find . -type f -name 'pom.xml'); do
            if grep -q "<version>$VERSION</version>" "$file"; then
              echo "Artifact version $VERSION found in $file."
              found=true
            fi
          done

          if [ "$found" = false ]; then
            echo "Artifact version $VERSION not found in any POM files."
            exit 1
          fi

      - name: List Artifacts and Dependencies
        run: |
          # Search for all POM files in the repository
          pom_files=$(find . -name 'pom.xml')

          # Loop through each POM file and extract artifact and dependency information
          for file in $pom_files; do
            echo "Artifacts and Dependencies in $file:"
            awk '/<artifactId>|<version>|<dependency>\s*<version>/' $file | awk -F '[<>]' '/<artifactId>|<version>|<dependency>\s*<version>/{print $3}' | paste -d ' ' - - -
          done          
