name: Developer Pre-Release Check

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to run the workflow on'
        required: true
        default: 'develop'
      VERSION:
        description: 'version_to_check'
        required: true

jobs:
  pre-release-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: List Artifacts and Dependency Versions
        run: |
          # Script to list artifacts and dependency versions
          find . -name 'pom.xml' -exec grep -E -o '<artifactId>[^<]+</artifactId>|<version>[^<]+</version>' {} \; | \
          awk 'BEGIN {ORS="\n"} {print} /^<artifactId>/ && /<version>.*<\/version>/ {printf("\n")}' | \
          grep -E '<artifactId>io.mosip[^<]+</artifactId>|<version>[^<]+</version>'


      - name: Replace Parameterized Values
        run: |
          # Script to replace parameterized values
          version_to_check="${{ inputs.VERSION }}"
          find . -name 'pom.xml' -exec sed -i "s/\${spring.boot.version}/${version_to_check}/g" {} \;

      - name: Check Dynamically Provided Artifact Version
        run: |
          # Script to check dynamically provided artifact version
          version_to_check="${{ inputs.VERSION }}"
          if ! grep -r -E "<artifactId>io.mosip[^<]+</artifactId>|<version>${version_to_check}</version>" --include="pom.xml" . | \
          grep "<version>${version_to_check}</version>" | awk -F: '{printf "%-70s %s\n", $1, $2}'; then
            echo "Error: Dynamically provided artifact version '${version_to_check}' not found for io.mosip artifacts."
            exit 1
          fi
