name: List Artifacts and Dependencies

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to run the workflow on'
        required: true
        default: 'develop'
      VERSION:
        description: 'Artifact version to search for'
        required: true

jobs:
  list-artifacts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: List Artifacts and Dependencies
        run: |
          # Search for all POM files in the repository
          pom_files=$(find . -name 'pom.xml')

          # Loop through each POM file and extract version information
          for file in $pom_files; do
            echo "Artifacts and Dependencies in $file:"
            xmllint --xpath "//*[local-name()='version']/text()" $file 2>/dev/null | awk -v version="$VERSION" '$1 == version {print $1}' || true
          done > $GITHUB_WORKSPACE/output.txt

      - name: Check Artifact Version
        run: |
          # Extract the dynamically provided artifact version from the user input
          VERSION=${{ github.event.inputs.VERSION }}

          # Search for the artifact version in the output file
          echo "Searching for artifact version: $VERSION"
          if [ -n "$(grep -E "$VERSION|${VERSION}-SNAPSHOT" $GITHUB_WORKSPACE/output.txt)" ]; then
            echo "Artifact version $VERSION found in the POM files."
          else
            echo "Artifact version $VERSION not found in any POM files."
            exit 1
          fi
